"""
processing/conversation_processor.py

Convert cleaned and normalized transcript data into a structured
conversation representation suitable for semantic chunking,
embeddings, and downstream analysis.

Pipeline:

    Audio
      ↓
    VAD
      ↓
    Chunker
      ↓
    Faster-Whisper
      ↓
    TranscriptBuilder
      ↓
    Cleaner
      ↓
    Normalizer
      ↓
    ConversationProcessor
      ↓
    SemanticChunker
      ↓
    Embeddings
      ↓
    Assessment


Important:
    This module does NOT:
        - remove PII
        - perform privacy redaction
        - generate embeddings
        - calculate mental-health scores
        - diagnose conditions
        - summarize the conversation

Privacy processing belongs in privacy/.
Embedding generation belongs in embeddings/.
Assessment belongs in assessment/.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


class ConversationProcessor:
    """
    Process transcript data into a consistent conversation structure.

    The processor is designed to work with the output generated by
    TranscriptBuilder and the Cleaner/Normalizer stages.

    Expected transcript structure:

        {
            "created_at": "...",
            "duration": 15.4,
            "segment_count": 3,
            "text": "...",
            "segments": [
                {
                    "start": 0.0,
                    "end": 4.2,
                    "text": "..."
                },
                ...
            ]
        }
    """

    def __init__(
        self,
        session_id: Optional[str] = None,
        speaker_label: str = "user",
        min_segment_length: int = 1,
        merge_short_segments: bool = True,
        max_merge_gap: float = 1.0,
    ):
        """
        Args:
            session_id:
                Identifier for the conversation/session.

            speaker_label:
                Label assigned to the current speaker.
                Defaults to "user".

            min_segment_length:
                Minimum number of characters for a segment to be retained.

            merge_short_segments:
                Merge very short transcript segments into neighboring
                segments when possible.

            max_merge_gap:
                Maximum time gap in seconds allowed when merging segments.
        """

        self.session_id = session_id
        self.speaker_label = speaker_label
        self.min_segment_length = max(1, min_segment_length)
        self.merge_short_segments = merge_short_segments
        self.max_merge_gap = max(0.0, max_merge_gap)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def process(
        self,
        transcript: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Process a complete transcript.

        Args:
            transcript:
                TranscriptBuilder output.

        Returns:
            Structured conversation document.
        """

        if not isinstance(transcript, dict):
            raise TypeError("transcript must be a dictionary")

        raw_segments = transcript.get("segments", [])

        if not isinstance(raw_segments, list):
            raise TypeError("transcript['segments'] must be a list")

        segments = self._prepare_segments(raw_segments)

        if self.merge_short_segments:
            segments = self._merge_short_segments(segments)

        text = self._build_text(segments)

        duration = self._calculate_duration(
            segments,
            transcript.get("duration", 0.0),
        )

        created_at = transcript.get("created_at")

        if not created_at:
            created_at = self._current_timestamp()

        conversation = {
            "session_id": self.session_id,
            "created_at": created_at,
            "processed_at": self._current_timestamp(),
            "speaker": self.speaker_label,
            "duration": duration,
            "segment_count": len(segments),
            "text": text,
            "segments": segments,
        }

        return conversation

    def process_text(
        self,
        text: str,
    ) -> Dict[str, Any]:
        """
        Process plain text when timing information is unavailable.

        This is useful for testing or for transcripts imported from
        another source.
        """

        if not isinstance(text, str):
            raise TypeError("text must be a string")

        text = text.strip()

        if not text:
            return {
                "session_id": self.session_id,
                "created_at": self._current_timestamp(),
                "processed_at": self._current_timestamp(),
                "speaker": self.speaker_label,
                "duration": 0.0,
                "segment_count": 0,
                "text": "",
                "segments": [],
            }

        segment = {
            "id": 0,
            "start": 0.0,
            "end": 0.0,
            "duration": 0.0,
            "speaker": self.speaker_label,
            "text": text,
        }

        return {
            "session_id": self.session_id,
            "created_at": self._current_timestamp(),
            "processed_at": self._current_timestamp(),
            "speaker": self.speaker_label,
            "duration": 0.0,
            "segment_count": 1,
            "text": text,
            "segments": [segment],
        }

    def process_segments(
        self,
        segments: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Process a list of transcript segments directly.
        """

        if not isinstance(segments, list):
            raise TypeError("segments must be a list")

        transcript = {
            "segments": segments,
            "duration": self._calculate_duration(
                segments,
                0.0,
            ),
        }

        return self.process(transcript)

    # ------------------------------------------------------------------
    # Segment preparation
    # ------------------------------------------------------------------

    def _prepare_segments(
        self,
        segments: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """
        Validate and standardize transcript segments.

        Timing information is preserved whenever available.
        """

        processed = []

        for index, segment in enumerate(segments):

            if not isinstance(segment, dict):
                continue

            text = segment.get("text", "")

            if text is None:
                continue

            text = str(text).strip()

            if len(text) < self.min_segment_length:
                continue

            start = self._safe_float(
                segment.get("start", 0.0)
            )

            end = self._safe_float(
                segment.get("end", start)
            )

            # Protect against invalid timing.
            if start < 0:
                start = 0.0

            if end < start:
                end = start

            duration = end - start

            processed_segment = {
                "id": index,
                "start": start,
                "end": end,
                "duration": duration,
                "speaker": segment.get(
                    "speaker",
                    self.speaker_label,
                ),
                "text": text,
            }

            # Preserve additional metadata from Whisper or future
            # transcription systems without modifying it.
            for key, value in segment.items():
                if key not in processed_segment:
                    processed_segment[key] = value

            processed.append(processed_segment)

        # Ensure chronological order.
        processed.sort(
            key=lambda item: item["start"]
        )

        return processed

    # ------------------------------------------------------------------
    # Short segment handling
    # ------------------------------------------------------------------

    def _merge_short_segments(
        self,
        segments: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """
        Merge very short neighboring segments.

        This helps avoid unnecessarily fragmented documents.

        Example:

            "I"
            "feel"
            "tired today."

        can become:

            "I feel tired today."

        Only nearby segments from the same speaker are merged.
        """

        if len(segments) <= 1:
            return segments

        result = []

        for segment in segments:

            if not result:
                result.append(segment)
                continue

            previous = result[-1]

            same_speaker = (
                previous.get("speaker")
                == segment.get("speaker")
            )

            gap = segment["start"] - previous["end"]

            is_short = (
                len(segment["text"].strip())
                < self.min_segment_length * 3
            )

            if (
                same_speaker
                and is_short
                and gap <= self.max_merge_gap
            ):
                result[-1] = self._merge_segments(
                    previous,
                    segment,
                )
            else:
                result.append(segment)

        # Reassign IDs after merging.
        for index, segment in enumerate(result):
            segment["id"] = index

        return result

    def _merge_segments(
        self,
        first: Dict[str, Any],
        second: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Merge two neighboring transcript segments.
        """

        merged = first.copy()

        first_text = first.get("text", "").strip()
        second_text = second.get("text", "").strip()

        if first_text and second_text:
            merged["text"] = f"{first_text} {second_text}"
        else:
            merged["text"] = first_text or second_text

        merged["end"] = max(
            first.get("end", 0.0),
            second.get("end", 0.0),
        )

        merged["start"] = min(
            first.get("start", 0.0),
            second.get("start", 0.0),
        )

        merged["duration"] = (
            merged["end"] - merged["start"]
        )

        return merged

    # ------------------------------------------------------------------
    # Text handling
    # ------------------------------------------------------------------

    def _build_text(
        self,
        segments: List[Dict[str, Any]],
    ) -> str:
        """
        Build a continuous conversation text from segments.

        No summarization or rewriting occurs.
        """

        texts = []

        for segment in segments:
            text = segment.get("text", "")

            if text:
                texts.append(text.strip())

        return " ".join(texts).strip()

    # ------------------------------------------------------------------
    # Timing
    # ------------------------------------------------------------------

    def _calculate_duration(
        self,
        segments: List[Dict[str, Any]],
        fallback: Any,
    ) -> float:
        """
        Calculate conversation duration.

        Uses the latest segment end time when available.
        """

        if segments:
            end_times = [
                self._safe_float(
                    segment.get("end", 0.0)
                )
                for segment in segments
            ]

            return max(end_times)

        return max(
            0.0,
            self._safe_float(fallback),
        )

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    @staticmethod
    def _safe_float(value: Any) -> float:
        """
        Safely convert a value to float.
        """

        try:
            result = float(value)

            if result != result:  # NaN check
                return 0.0

            if result == float("inf"):
                return 0.0

            if result == float("-inf"):
                return 0.0

            return result

        except (TypeError, ValueError):
            return 0.0

    @staticmethod
    def _current_timestamp() -> str:
        """
        Return an ISO-8601 UTC timestamp.
        """

        return datetime.now(timezone.utc).isoformat()


# ----------------------------------------------------------------------
# Convenience function
# ----------------------------------------------------------------------

def process_conversation(
    transcript: Dict[str, Any],
    session_id: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Convenience wrapper for processing a transcript.
    """

    processor = ConversationProcessor(
        session_id=session_id,
    )

    return processor.process(transcript)


# ----------------------------------------------------------------------
# Local test
# ----------------------------------------------------------------------

if __name__ == "__main__":

    print("=" * 70)
    print("CONVERSATION PROCESSOR TEST")
    print("=" * 70)

    transcript = {
        "created_at": "2026-01-01T12:00:00+00:00",
        "duration": 10.5,
        "segment_count": 4,
        "text": (
            "I don't know. "
            "I feel tired. "
            "Things have been difficult lately."
        ),
        "segments": [
            {
                "start": 0.0,
                "end": 1.2,
                "text": "I don't know.",
            },
            {
                "start": 1.3,
                "end": 1.7,
                "text": "I",
            },
            {
                "start": 1.8,
                "end": 2.5,
                "text": "feel tired.",
            },
            {
                "start": 4.0,
                "end": 10.5,
                "text": "Things have been difficult lately.",
            },
        ],
    }

    processor = ConversationProcessor(
        session_id="test-session-001",
    )

    result = processor.process(transcript)

    print("\nProcessed conversation:")
    print("-" * 70)

    print(f"Session ID:   {result['session_id']}")
    print(f"Speaker:      {result['speaker']}")
    print(f"Duration:     {result['duration']:.2f}s")
    print(f"Segments:     {result['segment_count']}")

    print("\nText:")
    print(result["text"])

    print("\nSegments:")
    for segment in result["segments"]:
        print(
            f"  [{segment['start']:.2f}s - "
            f"{segment['end']:.2f}s] "
            f"{segment['text']}"
        )

    # --------------------------------------------------------------
    # Plain text test
    # --------------------------------------------------------------

    print("\n" + "=" * 70)
    print("PLAIN TEXT TEST")
    print("=" * 70)

    text_result = processor.process_text(
        "I have been having a difficult week."
    )

    print("\nText:")
    print(text_result["text"])

    print("\nSegments:")
    print(text_result["segments"])

    print("\n" + "=" * 70)
    print("TEST COMPLETE")
    print("=" * 70)